### ISSUE TITLE
Enhance Chat

### ISSUE THREAD

**Issue by lebaudantoine** [numerique-gouv/meet#123]
## Feature Requests

Based on user feedback, we've compiled a list of requested chat-related features:

- [ ] Tag users in chat
- [ ] Add emoji support
- [ ] Create polls within the chat
- [ ] Export conversation to text or pad
- [ ] View previous message history
- [X] Enable clickable links

### To Do:

- [x] Use the same container as the participant list
- [x] Improve styling and layout

### Brainstorming Ideas:

- [ ] Integrate Tchap (suggested by @Anna-Livia)
- [ ] Allow simultaneous viewing of chat and participant list (suggested by @sampaccoud)

**Comment by Moustique82** [comment]
copy and paste an image in message
<img width="183" alt="image" src="https://github.com/user-attachments/assets/67dd22e4-6440-4736-bc25-2c248d629534">

**Comment by Vincentparisgithub** [comment]
i would  like to add:
. Possibility for the administrators to delete the messages of the others
. Possibility for each participants to delete or modify his owns messages
. To "reply" to a specific message
